spring:
  datasource:
    url: jdbc:mysql://${SQL_ADDRESS}/${SQL_DATABASE}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    generate-ddl: true
server:
  port: ${SERVER_PORT:8080}

leftovers:
  security:
    secret: ${JWT_SECRET}