name: Mirror to Work Remote
on:
  push:
    branches:
      - development
      - main
      
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: team-leftovers/leftovers-users
          source_branch: refs/remote/source/*
          destination_repo: ${{ secrets.WORK_REMOTE }}
          destination_branch: refs/heads/*
