name: Mirror to Work Remote
env:
  WORK_REMOTE: ${{ secrets.WORK_REMOTE }}
on:
  push:
    branches:
      - development
      - main
      
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch/Pull/Push
        run: |
          git remote add work $WORK_REMOTE
          git pull --no-rebase
          git push -u work --all
