name: Mirror to Work Remote
env:
  WORK_REMOTE: ${{ secrets.WORK_REMOTE }}
on:
  push:
    branches:
      - development
      - main
      
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch all changes
        run: git fetch --all
        
      - name: Pull all changes
        run: git pull --all
      
      - name: Setup new Remote
        run: git remote add work $WORK_REMOTE
        
      - name: Pull from Remote
        run: git pull work --all
        
      - name: Push to Remote
        run: git push -u work --all
